[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "regress-lm"
version = "0.0.0"
description = "Library for text-to-text regression, applicable to any input string representation and allows pretraining and fine-tuning over multiple regression tasks."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "absl-py",
    "numpy",
    "ordered-set",
    "gcsfs",  # For downloading T5-vocabulary.
    "tokenizers",
    "sentencepiece",  # For default tokenization + creating custom vocabs.
    "torch>=2.2.0",  # Guarantees stable SDPA + native FlashAttention-2
]

[tool.setuptools.packages.find]
include = ["regress_lm", "regress_lm.*"]

[project.optional-dependencies]
extras = [
    "transformers>5.0.0",  # for T5Gemma-1 and 2 model.
    "peft>=0.19.0",  # for LoRA fine-tuning.
    # "mamba-ssm[causal-conv1d]",  # for Mamba SSM model. cuda errors ATM.
]
