title: "Quantitative Inductive Machines"
description: "Quantitative Inductive Machines (QIM): Sequence-to-sequence regression with language models."
theme: jekyll-theme-cayman
baseurl: ""
url: "https://qim-paper.io"
